CREATE TABLE IF NOT EXISTS email_scans (
  scan_id TEXT PRIMARY KEY, message_id TEXT NOT NULL, scanned_at TIMESTAMPTZ NOT NULL, result_json JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS scan_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, scan_id TEXT NOT NULL REFERENCES email_scans(scan_id),
  message_id TEXT NOT NULL, action TEXT NOT NULL CHECK (action IN ('reported_suspicious', 'view_full_analysis')), created_at TIMESTAMPTZ NOT NULL
);
DELETE FROM scan_feedback a USING scan_feedback b WHERE a.id > b.id AND a.scan_id = b.scan_id AND a.action = b.action;
CREATE UNIQUE INDEX IF NOT EXISTS scan_feedback_action_unique_idx ON scan_feedback(scan_id, action);
